### ISSUE TITLE
Project build fails in older (2018.2) Intellij versions

### ISSUE THREAD

**Issue by the-sauce** [Quillraven/SimpleKtxGame#8]
@Quillraven I had [this](https://youtrack.jetbrains.com/issue/KT-29127) problem with your build.

Updating to the newest Intellij version solved my issues.

Still wanting to share it here to save others the time I wasted looking for a solution.

Perhaps you could mention it in the next version of your tutorial.

**Comment by Quillraven** [comment]
@the-sauce 
Thank you for the information! I don't remember which version of Intellij I used but anyway I will try to update the setup section of the tutorial since libgdx 1.9.10 was released now and it already solves a couple of gradle issues.

I hope I have time this week and I let you know when the setup section is updated.

**Comment by Quillraven** [comment]
I have updated the wiki setup page and I also mentioned how to get the newest libgdx/libktx version that you can use in the "app" section.

I tried it with IntelliJ 2019.2 and LibGDX 1.9.10 setup from today (2019-08-18). Seems like all the things that are mentioned in the setup part are no longer needed and you also no longer need to specify the assets folder seperately (I removed those parts to reduce the confusion of beginners).

I will close this issue for now. Please let me know if everything is also working for you! 

Thanks
